//! Parity for the VAD segmentation layer against upstream's own
//! `get_speech_timestamps`.
//!
//! `tests/silero_vad_parity.rs` pins the network's per-chunk probabilities.
//! This pins the layer above it: the thresholds, duration rules and padding
//! that turn those probabilities into utterance boundaries. A port can match
//! the model to 1e-6 and still emit the wrong segments — the rules interact,
//! and upstream's control flow is asymmetric in two places.
//!
//! Neither the weights, the audio fixture nor the reference JSON is checked in,
//! so these tests skip unless `SILERO_VAD_WEIGHTS` / `SILERO_VAD_FIXTURE` /
//! `SILERO_VAD_TIMESTAMPS` point at them, or `BOOSTR_MODELS_DIR` contains
//! `silero-vad/`.
//!
//! The reference JSON was generated by running upstream's
//! `get_speech_timestamps` over the same 60 s of audio held in
//! `silero_vad_fixture.safetensors`:
//!
//! ```json
//! { "sample_rate": 16000, "num_samples": 960000,
//!   "cases": { "<name>": { "params": {...}, "segments": [[start, end], ...] } } }
//! ```
//!
//! The longest natural segment in that audio is 4.16 s, so the max-speech
//! cases cap at 2 s — a cap above the longest segment reproduces `defaults`
//! and exercises none of the splitting code.
//!
//! Boundaries are integer sample counts, so every assertion is exact equality.
//! Do NOT introduce a tolerance: an off-by-one here means a rule fired on the
//! wrong chunk, not that the arithmetic is imprecise.

use std::collections::BTreeMap;
use std::path::Path;

use boostr::model::audio::{SileroVad, SpeechSegment, VadSegmentOptions};
use boostr::nn::VarMap;
use numr::runtime::cpu::{CpuClient, CpuDevice, CpuRuntime};
use serde::Deserialize;

mod common;
use common::{model_fixture, skip_notice};

/// The reference file's per-case parameters. Every field is optional: a case
/// only lists what it changes from upstream's defaults, which are the same
/// values [`VadSegmentOptions::default`] carries.
#[derive(Debug, Default, Deserialize)]
struct CaseParams {
    threshold: Option<f32>,
    neg_threshold: Option<f32>,
    min_speech_duration_ms: Option<u32>,
    /// Absent means no cap — JSON cannot hold an infinity.
    max_speech_duration_s: Option<f32>,
    min_silence_duration_ms: Option<u32>,
    speech_pad_ms: Option<u32>,
    min_silence_at_max_speech_ms: Option<u32>,
    use_max_poss_sil_at_max_speech: Option<bool>,
}

impl CaseParams {
    fn to_options(&self) -> VadSegmentOptions {
        let mut opts = VadSegmentOptions::default();
        if let Some(v) = self.threshold {
            opts.threshold = v;
        }
        if self.neg_threshold.is_some() {
            opts.neg_threshold = self.neg_threshold;
        }
        if let Some(v) = self.min_speech_duration_ms {
            opts.min_speech_duration_ms = v;
        }
        if let Some(v) = self.max_speech_duration_s {
            opts.max_speech_duration_s = v;
        }
        if let Some(v) = self.min_silence_duration_ms {
            opts.min_silence_duration_ms = v;
        }
        if let Some(v) = self.speech_pad_ms {
            opts.speech_pad_ms = v;
        }
        if let Some(v) = self.min_silence_at_max_speech_ms {
            opts.min_silence_at_max_speech_ms = v;
        }
        if let Some(v) = self.use_max_poss_sil_at_max_speech {
            opts.use_max_possible_silence_at_max_speech = v;
        }
        opts
    }
}

#[derive(Debug, Deserialize)]
struct Case {
    #[serde(default)]
    params: CaseParams,
    /// `[start, end]` sample pairs, half-open.
    segments: Vec<[usize; 2]>,
}

#[derive(Debug, Deserialize)]
struct Reference {
    sample_rate: usize,
    num_samples: usize,
    /// Keyed by case name; `BTreeMap` so the report order is stable.
    cases: BTreeMap<String, Case>,
}

fn load_reference(path: &Path) -> Reference {
    let bytes = std::fs::read(path).unwrap_or_else(|e| panic!("reading {}: {e}", path.display()));
    serde_json::from_slice(&bytes).unwrap_or_else(|e| panic!("parsing {}: {e}", path.display()))
}

fn load_model() -> Option<(SileroVad<CpuRuntime>, CpuClient)> {
    let path = model_fixture(
        "SILERO_VAD_WEIGHTS",
        "silero-vad/silero_vad_16k.safetensors",
    )?;
    let device = CpuDevice::new();
    let client = CpuClient::new(device.clone());
    match SileroVad::<CpuRuntime>::from_safetensors(&path, &device) {
        Ok(vad) => Some((vad, client)),
        Err(e) => panic!("failed to load {}: {e}", path.display()),
    }
}

fn load_audio() -> Option<Vec<f32>> {
    let path = model_fixture(
        "SILERO_VAD_FIXTURE",
        "silero-vad/silero_vad_fixture.safetensors",
    )?;
    let device = CpuDevice::new();
    let map = match VarMap::<CpuRuntime>::from_safetensors(&path, &device) {
        Ok(map) => map,
        Err(e) => panic!("failed to load {}: {e}", path.display()),
    };
    let input = map
        .get_tensor("input")
        .unwrap_or_else(|e| panic!("fixture is missing `input`: {e}"));
    Some(input.to_vec::<f32>())
}

/// Report the first differing segment before asserting, so a failure names the
/// boundary that moved instead of dumping two lists.
fn compare(name: &str, ours: &[SpeechSegment], reference: &[[usize; 2]]) {
    eprintln!(
        "silero vad segments [{name}]: ours {}, reference {}",
        ours.len(),
        reference.len()
    );
    for i in 0..ours.len().max(reference.len()) {
        let mine = ours.get(i).map(|s| [s.start, s.end]);
        let theirs = reference.get(i).copied();
        if mine != theirs {
            eprintln!("  first mismatch at {i}: ours {mine:?}, reference {theirs:?}");
            break;
        }
    }
    assert_eq!(
        ours.len(),
        reference.len(),
        "[{name}] segment count: ours {}, reference {}",
        ours.len(),
        reference.len()
    );
    for (i, (s, r)) in ours.iter().zip(reference.iter()).enumerate() {
        assert_eq!(
            [s.start, s.end],
            *r,
            "[{name}] segment {i}: ours [{}, {}), reference [{}, {})",
            s.start,
            s.end,
            r[0],
            r[1]
        );
    }
}

#[test]
fn silero_vad_segments_match_upstream_get_speech_timestamps() {
    let Some(path) = model_fixture(
        "SILERO_VAD_TIMESTAMPS",
        "silero-vad/silero_vad_timestamps.json",
    ) else {
        skip_notice("silero vad timestamps reference", "SILERO_VAD_TIMESTAMPS");
        return;
    };
    let Some((vad, client)) = load_model() else {
        skip_notice("silero vad weights", "SILERO_VAD_WEIGHTS");
        return;
    };
    let Some(audio) = load_audio() else {
        skip_notice("silero vad fixture", "SILERO_VAD_FIXTURE");
        return;
    };

    let reference = load_reference(&path);
    assert_eq!(
        audio.len(),
        reference.num_samples,
        "fixture audio is {} samples, reference was generated over {}",
        audio.len(),
        reference.num_samples
    );
    assert_eq!(
        vad.config().sample_rate,
        reference.sample_rate,
        "model geometry and reference disagree on the sample rate"
    );
    assert!(!reference.cases.is_empty(), "reference lists no cases");

    for (name, case) in &reference.cases {
        let opts = case.params.to_options();
        let ours = vad
            .speech_timestamps(&client, &audio, &opts)
            .unwrap_or_else(|e| panic!("[{name}] segmentation failed: {e}"));
        compare(name, &ours, &case.segments);
    }
}
